In [3]:
import numpy as np

In [4]:
print(np.__version__)


1.19.4


In [5]:
x = [2, 3, 4, 5, 6]
nums = np.array([2, 3, 4, 5, 6])
type(nums)

numpy.ndarray

In [8]:
#1D array
arr = np.arange(10)
arr
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#2d array
b = np.arange(12).reshape(4,3)           
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [13]:
#3darray
c = np.arange(24).reshape(2,3,4)  
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [15]:
# more than one dimensions 
 
a = np.array([[1, 2], [3, 4]]) 
print (a)

[[1 2]
 [3 4]]


In [17]:
# minimum dimensions 
 
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print (a)

[[1 2 3 4 5]]


In [18]:
# dtype parameter 

a = np.array([1, 2, 3], dtype = complex) 
print (a)

[1.+0.j 2.+0.j 3.+0.j]


In [19]:
#boolen array
bool_arr = np.array([1, 0.5, 0, None, 'a', '', True, False], dtype=bool)
print(bool_arr)


[ True  True False False  True False  True False]


In [20]:
#ndim
a = np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


In [21]:
#itemsize
a = np.array([(1,2,3)])
print(a.itemsize)

4


In [22]:
#dtype
a = np.array([(1,2,3)])
print(a.dtype)

int32


In [23]:
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


In [25]:
#slicing
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0:,2])

[3 5]


In [26]:
a=np.array([(8,9),(10,11),(12,13)])
print(a[0:2,1])

[ 9 11]


In [27]:
a=np.linspace(1,3,10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [28]:
a= np.array([1,2,3])
print(a.min())

1


In [29]:
a= np.array([1,2,3])
print(a.max())

3


In [30]:
a= np.array([1,2,3])
print(a.sum())

6


In [31]:
a=np.array([(1,2,3),(3,4,5,)])
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]


In [35]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x-y)

[[0 0 0]
 [0 0 0]]


In [36]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x*y)

[[ 1  4  9]
 [ 9 16 25]]


In [37]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x/y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [38]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]


In [39]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.hstack((x,y)))

[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


In [40]:
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel())

[1 2 3 3 4 5]


In [41]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [5]:
#zero numpy array
array1d = np.zeros(3)
print(array1d)

[0. 0. 0.]


In [6]:
array2d = np.zeros((2, 4))
print(array2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
#logspace array
thearray = np.logspace(5, 10, num=10, base=10000000.0, dtype=float)
print(thearray)

[1.00000000e+35 7.74263683e+38 5.99484250e+42 4.64158883e+46
 3.59381366e+50 2.78255940e+54 2.15443469e+58 1.66810054e+62
 1.29154967e+66 1.00000000e+70]


In [8]:
#generate random number array
print(np.random.rand(3, 2))#uniformly distributed

[[0.81427675 0.92005866]
 [0.99978469 0.90147236]
 [0.98286264 0.71621553]]


In [9]:
print(np.random.randn(3, 2))#normally distributed value

[[ 0.03476295  1.378293  ]
 [ 0.63882112 -0.68103495]
 [ 0.877554    0.18573238]]


In [10]:
# Uniformly distributed integers in a given range.
print(np.random.randint(2, size=10))
print(np.random.randint(5, size=(2, 4)))

[1 0 1 0 0 0 1 1 0 0]
[[1 4 3 1]
 [1 4 2 0]]


In [12]:
# identity and digonal array
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
print(np.diag(np.arange(0, 8, 2)))

[[0 0 0 0]
 [0 2 0 0]
 [0 0 4 0]
 [0 0 0 6]]


In [14]:
print(np.diag(np.diag(np.arange(9).reshape((3,3)))))

[[0 0 0]
 [0 4 0]
 [0 0 8]]


In [15]:
#numpy indexing example
array1d = np.array([1, 2, 3, 4, 5, 6])
print(array1d[0])   # Get first value
print(array1d[-1])  # Get last value
print(array1d[3])   # Get 4th value from first
print(array1d[-5])  # Get 5th value from last

1
6
4
2


In [16]:
# Get multiple values
print(array1d[[0, -1]])

[1 6]


In [19]:
#numpy indexing in multidimensional array
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array3d)
 
print(array3d[0, 0, 0])
print(array3d[0, 0, 1])
print(array3d[0, 0, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3


In [21]:
#joining and stacking of numpy array
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
 
# Stack arrays in sequence horizontally (column wise).
arrayH = np.hstack((array1, array2))
print(arrayH)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [22]:
# Stack arrays in sequence vertically (row wise).
arrayV = np.vstack((array1, array2))
print(arrayV)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
# Appending arrays after each other, along a given axis.
arrayC = np.concatenate((array1, array2))
print(arrayC)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
# Append values to the end of an array.
arrayA = np.append(array1, array2, axis=0)
print(arrayA)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [25]:
arrayA = np.append(array1, array2, axis=1)
print(arrayA)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [26]:
#numpy elementry matha metical function
array1 = np.array([[10, 20, 30], [40, 50, 60]])
 
print(np.sin(array1))

[[-0.54402111  0.91294525 -0.98803162]
 [ 0.74511316 -0.26237485 -0.30481062]]


In [27]:
print(np.cos(array1))

[[-0.83907153  0.40808206  0.15425145]
 [-0.66693806  0.96496603 -0.95241298]]


In [28]:
print(np.tan(array1))

[[ 0.64836083  2.23716094 -6.4053312 ]
 [-1.11721493 -0.27190061  0.32004039]]


In [29]:
print(np.sqrt(array1))

[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]


In [30]:
print(np.exp(array1))

[[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [2.35385267e+17 5.18470553e+21 1.14200739e+26]]


In [31]:
print(np.log10(array1))

[[1.         1.30103    1.47712125]
 [1.60205999 1.69897    1.77815125]]


In [32]:
#element wise mathematicialoperation
array1 = np.array([[10, 20, 30], [40, 50, 60]])
array2 = np.array([[2, 3, 4], [4, 6, 8]])
array3 = np.array([[-2, 3.5, -4], [4.05, -6, 8]])
print(np.add(array1, array2))

[[12 23 34]
 [44 56 68]]


In [33]:
print(np.power(array1, array2))

[[        100        8000      810000]
 [    2560000 -1554869184 -1686044672]]


In [34]:
print(np.remainder((array2), 5))

[[2 3 4]
 [4 1 3]]


In [35]:
print(np.reciprocal(array3))

[[-0.5         0.28571429 -0.25      ]
 [ 0.24691358 -0.16666667  0.125     ]]


In [36]:
print(np.sign(array3))

[[-1.  1. -1.]
 [ 1. -1.  1.]]


In [37]:

print(np.ceil(array3))

[[-2.  4. -4.]
 [ 5. -6.  8.]]


In [38]:
print(np.round(array3))

[[-2.  4. -4.]
 [ 4. -6.  8.]]


In [39]:
#numpy aggregate and staticial function
array1 = np.array([[10, 20, 30], [40, 50, 60]])
 
print("Mean: ", np.mean(array1))

Mean:  35.0


In [40]:
print("Std: ", np.std(array1))

Std:  17.07825127659933


In [41]:
print("Var: ", np.var(array1))

Var:  291.6666666666667


In [42]:
print("Sum: ", np.sum(array1))

Sum:  210


In [43]:
print("Prod: ", np.prod(array1))

Prod:  720000000
